### ISSUE TITLE
Сделать карусель с фотографиями на главную

### ISSUE THREAD

**Issue by Anastacia-Tesli** [BKonstantine/maxvel_frontend#68]
Лучше подставить 3-4 реальных фото например из стока, чтобы не было так грустно.
Наверное можно сделать, чтобы они сами перелистывались через определенный интервал🤔

**Comment by Anastacia-Tesli** [comment]
Предлагаю эту библиотеку https://www.npmjs.com/package/react-slick
С вот этим методом https://react-slick.neostack.com/docs/example/pause-on-hover

**Comment by BKonstantine** [comment]
Хорошие предложения, давай!
